## Obtaining the Efficient Frontier - Part III

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Ok, let’s continue the exercise from the last lecture.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# Load CSV data for 2 assets (WMT, FB)
assets = ['WMT', 'FB']
pf_data = pd.read_csv('Markowitz_Data.csv', index_col='Date')
pf_data

PG        ^GSPC
Date                              
2010-01-04  61.119999  1132.989990
2010-01-05  61.139999  1136.520020
2010-01-06  60.849998  1137.140015
2010-01-07  60.520000  1141.689941
2010-01-08  60.439999  1144.979980
...               ...          ...
2017-03-20  91.220001  2373.469971
2017-03-21  91.190002  2344.020020
2017-03-22  90.989998  2348.449951
2017-03-23  90.769997  2345.959961
2017-03-24  90.570000  2343.979980

[1819 rows x 2 columns]

In [2]:
log_returns = np.log(pf_data / pf_data.shift(1))

num_assets = len(assets)

weights = np.random.random(num_assets)
weights /= np.sum(weights)
weights

array([0.6985674, 0.3014326])

Now, estimate the expected Portfolio Return, Variance, and Volatility.

Expected Portfolio Return:

In [3]:
np.sum(weights * log_returns.mean()) * 250

0.06791444645673579

Expected Portfolio Variance:

In [4]:
np.dot(weights.T, np.dot(log_returns.cov() * 250, weights))

0.017380311507396554

Expected Portfolio Volatility:

In [5]:
np.sqrt(np.dot(weights.T,np.dot(log_returns.cov() * 250, weights)))

0.13183440942104818

***

The rest of this exercise will be a reproduction of what we did in the previous video.

1)	Create two empty lists. Name them pf_returns and pf_volatilites.

In [6]:
pf_returns = []
pf_volatilities = []

2)	Create a loop with 1,000 iterations that will generate random weights, summing to 1, and will append the obtained values for the portfolio returns and the portfolio volatilities to pf_returns and pf_volatilities, respectively.

In [7]:
for x in range (1000):
    weights = np.random.random(num_assets)
    weights /= np.sum(weights)
    pf_returns.append(np.sum(weights * log_returns.mean()) * 250)
    pf_volatilities.append(np.sqrt(np.dot(weights.T,np.dot(log_returns.cov() * 250, weights))))
    
pf_returns, pf_volatilities

([0.07630193013192832,
  0.06952523687758656,
  0.08535074244816222,
  0.059626866040657686,
  0.07143312154850563,
  0.05830159469635857,
  0.09230343024747031,
  0.09551753964520975,
  0.09234048605304458,
  0.07072748862871983,
  0.06654992293102195,
  0.09185436761827466,
  0.058167595302458075,
  0.05427711847025439,
  0.0858643522417823,
  0.07690351165069921,
  0.08818911979086085,
  0.07515086935822238,
  0.07796897508678924,
  0.057195407642977925,
  0.09611922839569387,
  0.08756496742772536,
  0.09325663809856799,
  0.08312693263741763,
  0.06976418743390633,
  0.08209246458481648,
  0.07551540224124421,
  0.06634492817709194,
  0.071280878761164,
  0.0610819708986433,
  0.06172750664774096,
  0.06743519257870434,
  0.07406837694934847,
  0.07998424722683493,
  0.07919352929659357,
  0.06625467578919998,
  0.09596166903222929,
  0.08138784774795763,
  0.07139402071436537,
  0.06501714467445313,
  0.0880127177280694,
  0.09418638649432405,
  0.08106319134877008,
  0.066887516

3)	Transform the obtained lists into NumPy arrays and reassign them to pf_returns and pf_volatilites. Once you have done that, the two objects will be NumPy arrays. 

In [8]:
pf_returns = np.array(pf_returns)
pf_volatilities = np.array(pf_volatilities)

pf_returns, pf_volatilities

(array([0.07630193, 0.06952524, 0.08535074, 0.05962687, 0.07143312,
        0.05830159, 0.09230343, 0.09551754, 0.09234049, 0.07072749,
        0.06654992, 0.09185437, 0.0581676 , 0.05427712, 0.08586435,
        0.07690351, 0.08818912, 0.07515087, 0.07796898, 0.05719541,
        0.09611923, 0.08756497, 0.09325664, 0.08312693, 0.06976419,
        0.08209246, 0.0755154 , 0.06634493, 0.07128088, 0.06108197,
        0.06172751, 0.06743519, 0.07406838, 0.07998425, 0.07919353,
        0.06625468, 0.09596167, 0.08138785, 0.07139402, 0.06501714,
        0.08801272, 0.09418639, 0.08106319, 0.06688752, 0.07766042,
        0.08447919, 0.07522404, 0.05603017, 0.06471047, 0.06812727,
        0.06844776, 0.08997989, 0.05945549, 0.07768615, 0.06797176,
        0.08590238, 0.0885087 , 0.06061875, 0.05734707, 0.0648087 ,
        0.07290226, 0.07048946, 0.05802066, 0.07339883, 0.07687638,
        0.0634396 , 0.07001298, 0.08159917, 0.08334491, 0.0679892 ,
        0.07419137, 0.0758007 , 0.0631738 , 0.07

Now, create a dictionary, called portfolios, whose keys are the strings “Return” and “Volatility” and whose values are the NumPy arrays pf_returns and pf_volatilities. 

In [9]:
# Create dictionary with Return and Volatility
portfolios = {
    'Return': pf_returns,
    'Volatility': pf_volatilities
}

portfolios = pd.DataFrame(portfolios)
portfolios.head()

Return  Volatility
0  0.076302    0.131048
1  0.069525    0.131311
2  0.085351    0.135525
3  0.059627    0.137204
4  0.071433    0.130919

Finally, plot the data from the portfolios dictionary on a graph. Let the x-axis represent the volatility data from the portfolios dictionary and the y-axis – the data about rates of return. <br />
Organize your chart well and make sure you have labeled both the x- and the y- axes.

In [10]:
# Plot the Efficient Frontier for 2 assets
portfolios.plot(x='Volatility', y='Return', kind='scatter', figsize=(10, 6))
plt.xlabel('Expected Volatility')
plt.ylabel('Expected Return')
plt.title('Efficient Frontier - 2 Assets (WMT, FB)')

Text(0.5, 1.0, 'Efficient Frontier - 2 Assets (WMT, FB)')

******

What do you think would happen if you re-created the Markowitz Efficient Frontier for 3 stocks? The code you have created is supposed to accommodate easily the addition of a third stock, say British Petroleum (‘BP’). Insert it in your data and re-run the code (you can expand the “Cell” list from the Jupyter menu and click on “Run All” to execute all the cells at once!). <br />

How would you interpret the obtained graph? 


In [11]:
# Load 3-asset data (WMT, FB, BP)
assets = ['WMT', 'FB', 'BP']
pf_data = pd.read_csv('WMT_FB_BP_2014_2017.csv', index_col='Date')

# Recalculate log returns and num_assets
log_returns = np.log(pf_data / pf_data.shift(1))
num_assets = len(assets)

# Generate new random weights
weights = np.random.random(num_assets)
weights /= np.sum(weights)
weights

array([0.05218783, 0.5059767 , 0.44183547])

Expected Portfolio Return:

In [12]:
# Expected portfolio return for 3 assets
np.sum(weights * log_returns.mean()) * 250

0.1616900669312623

Expected Portfolio Variance:

In [13]:
# Expected portfolio variance for 3 assets
np.dot(weights.T, np.dot(log_returns.cov() * 250, weights))

0.03710803669117392

Expected Portfolio Volatility:

In [14]:
# Expected portfolio volatility for 3 assets
np.sqrt(np.dot(weights.T, np.dot(log_returns.cov() * 250, weights)))

0.19263446392370687

*****

In [15]:
# Re-run simulation for 3 assets
pf_returns = []
pf_volatilities = []

for x in range(1000):
    weights = np.random.random(num_assets)
    weights /= np.sum(weights)
    pf_returns.append(np.sum(weights * log_returns.mean()) * 250)
    pf_volatilities.append(np.sqrt(np.dot(weights.T, np.dot(log_returns.cov() * 250, weights))))

pf_returns = np.array(pf_returns)
pf_volatilities = np.array(pf_volatilities)

In [16]:
# Create portfolios DataFrame for 3 assets
portfolios = pd.DataFrame({'Return': pf_returns, 'Volatility': pf_volatilities})
portfolios.head()

Return  Volatility
0  0.224258    0.213546
1  0.177525    0.183831
2  0.089348    0.145251
3  0.176043    0.168030
4  0.157607    0.186236

In [17]:
portfolios.plot(x='Volatility', y='Return', kind='scatter', figsize=(10, 6));
plt.xlabel('Expected Volatility')
plt.ylabel('Expected Return')

Text(0, 0.5, 'Expected Return')