## Obtaining the Efficient Frontier - Part III

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Ok, let’s continue the exercise from the last lecture.

In [1]:
import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
%matplotlib inline

# Start with 2 assets (WMT, META)
assets = ['WMT', 'META']

# Download Adjusted Close prices
pf_data = yf.download(assets, start='2014-01-01', auto_adjust=False, progress=False)['Adj Close']
pf_data = pf_data[assets]

In [2]:
log_returns = np.log(pf_data / pf_data.shift(1))

num_assets = len(assets)

weights = np.random.random(num_assets)
weights /= np.sum(weights)
weights

array([0.47459975, 0.52540025])

Now, estimate the expected Portfolio Return, Variance, and Volatility.

Expected Portfolio Return:

In [3]:
np.sum(weights * log_returns.mean()) * 250

0.16957549453937454

Expected Portfolio Variance:

In [4]:
np.dot(weights.T, np.dot(log_returns.cov() * 250, weights))

0.056888830269757225

Expected Portfolio Volatility:

In [5]:
np.sqrt(np.dot(weights.T,np.dot(log_returns.cov() * 250, weights)))

0.23851379471585543

***

The rest of this exercise will be a reproduction of what we did in the previous video.

1)	Create two empty lists. Name them pf_returns and pf_volatilites.

In [6]:
pf_returns = []
pf_volatilities = []

2)	Create a loop with 1,000 iterations that will generate random weights, summing to 1, and will append the obtained values for the portfolio returns and the portfolio volatilities to pf_returns and pf_volatilities, respectively.

In [7]:
for x in range (1000):
    weights = np.random.random(num_assets)
    weights /= np.sum(weights)
    pf_returns.append(np.sum(weights * log_returns.mean()) * 250)
    pf_volatilities.append(np.sqrt(np.dot(weights.T,np.dot(log_returns.cov() * 250, weights))))
    
pf_returns, pf_volatilities

([0.18095248974201944,
  0.13834594266962483,
  0.18236478246300672,
  0.15651315561969759,
  0.14139223291203704,
  0.15677759999411822,
  0.1862299013527952,
  0.16927652012805977,
  0.18246019618107612,
  0.1743034987949173,
  0.1476508598680496,
  0.15727331833671332,
  0.19631373730665808,
  0.18379145793238638,
  0.16803330387847007,
  0.15859929801810785,
  0.16358064197069136,
  0.1753108156199239,
  0.17436826194200272,
  0.1745314108099066,
  0.17670896681561302,
  0.19104673907102476,
  0.1468609099424149,
  0.16630788256548598,
  0.20151750847907018,
  0.1640064797885393,
  0.1704426647339173,
  0.1974952945225198,
  0.15473456280227046,
  0.20191704216243614,
  0.15732565867862852,
  0.18475731495498718,
  0.17880768093630311,
  0.16599288219411218,
  0.16689136561560694,
  0.17364912201447072,
  0.19206477495613264,
  0.17140736370273,
  0.18298455982164433,
  0.15711492102607397,
  0.16495243739503226,
  0.15516451836739142,
  0.16094452679228194,
  0.17463325388074855,


3)	Transform the obtained lists into NumPy arrays and reassign them to pf_returns and pf_volatilites. Once you have done that, the two objects will be NumPy arrays. 

In [8]:
pf_returns = np.array(pf_returns)
pf_volatilities = np.array(pf_volatilities)

pf_returns, pf_volatilities

(array([0.18095249, 0.13834594, 0.18236478, 0.15651316, 0.14139223,
        0.1567776 , 0.1862299 , 0.16927652, 0.1824602 , 0.1743035 ,
        0.14765086, 0.15727332, 0.19631374, 0.18379146, 0.1680333 ,
        0.1585993 , 0.16358064, 0.17531082, 0.17436826, 0.17453141,
        0.17670897, 0.19104674, 0.14686091, 0.16630788, 0.20151751,
        0.16400648, 0.17044266, 0.19749529, 0.15473456, 0.20191704,
        0.15732566, 0.18475731, 0.17880768, 0.16599288, 0.16689137,
        0.17364912, 0.19206477, 0.17140736, 0.18298456, 0.15711492,
        0.16495244, 0.15516452, 0.16094453, 0.17463325, 0.1347166 ,
        0.16267001, 0.17082934, 0.15115558, 0.15405371, 0.1899413 ,
        0.19008955, 0.17762929, 0.1641916 , 0.15713203, 0.17648793,
        0.13712534, 0.18557112, 0.19369661, 0.1643396 , 0.16674027,
        0.16599067, 0.17226292, 0.16770691, 0.20206876, 0.17400833,
        0.14881171, 0.19883579, 0.14078566, 0.14280865, 0.16535755,
        0.14607287, 0.17806584, 0.18325922, 0.17

Now, create a dictionary, called portfolios, whose keys are the strings “Return” and “Volatility” and whose values are the NumPy arrays pf_returns and pf_volatilities. 

In [9]:
# Create dictionary with Return and Volatility arrays
portfolios = {
    'Return': pf_returns,
    'Volatility': pf_volatilities
}

portfolios = pd.DataFrame(portfolios)
portfolios.head()

Return  Volatility
0  0.180952    0.280148
1  0.138346    0.200218
2  0.182365    0.285902
3  0.156513    0.205636
4  0.141392    0.197447

Finally, plot the data from the portfolios dictionary on a graph. Let the x-axis represent the volatility data from the portfolios dictionary and the y-axis – the data about rates of return. <br />
Organize your chart well and make sure you have labeled both the x- and the y- axes.

In [10]:
# Plot the Efficient Frontier
portfolios.plot(x='Volatility', y='Return', kind='scatter', figsize=(10, 6))
plt.xlabel('Expected Volatility')
plt.ylabel('Expected Return')
plt.title('Efficient Frontier - 2 Assets')

Text(0.5, 1.0, 'Efficient Frontier - 2 Assets')

******

What do you think would happen if you re-created the Markowitz Efficient Frontier for 3 stocks? The code you have created is supposed to accommodate easily the addition of a third stock, say British Petroleum (‘BP’). Insert it in your data and re-run the code (you can expand the “Cell” list from the Jupyter menu and click on “Run All” to execute all the cells at once!). <br />

How would you interpret the obtained graph? 


In [11]:
# Expand to 3 assets: add BP (British Petroleum)
assets = ['WMT', 'META', 'BP']

# Re-download data with 3 assets
pf_data = yf.download(assets, start='2014-01-01', auto_adjust=False, progress=False)['Adj Close']
pf_data = pf_data[assets]

# Recalculate log returns and num_assets
log_returns = np.log(pf_data / pf_data.shift(1))
num_assets = len(assets)

# Generate new random weights
weights = np.random.random(num_assets)
weights /= np.sum(weights)
weights

array([0.34130169, 0.59466081, 0.0640375 ])

Expected Portfolio Return:

In [12]:
# Expected portfolio return for 3 assets
np.sum(weights * log_returns.mean()) * 250

0.16809582038522122

Expected Portfolio Variance:

In [13]:
# Expected portfolio variance for 3 assets
np.dot(weights.T, np.dot(log_returns.cov() * 250, weights))

0.06417415672616746

Expected Portfolio Volatility:

In [14]:
# Expected portfolio volatility for 3 assets
np.sqrt(np.dot(weights.T, np.dot(log_returns.cov() * 250, weights)))

0.253326186420132

*****

In [15]:
# Re-run simulation for 3 assets
pf_returns = []
pf_volatilities = []

for x in range(1000):
    weights = np.random.random(num_assets)
    weights /= np.sum(weights)
    pf_returns.append(np.sum(weights * log_returns.mean()) * 250)
    pf_volatilities.append(np.sqrt(np.dot(weights.T, np.dot(log_returns.cov() * 250, weights))))

pf_returns = np.array(pf_returns)
pf_volatilities = np.array(pf_volatilities)

In [16]:
# Create portfolios DataFrame for 3 assets
portfolios = pd.DataFrame({'Return': pf_returns, 'Volatility': pf_volatilities})
portfolios.head()

Return  Volatility
0  0.094740    0.187450
1  0.070089    0.226768
2  0.094641    0.201523
3  0.132132    0.196839
4  0.139860    0.236173

In [17]:
portfolios.plot(x='Volatility', y='Return', kind='scatter', figsize=(10, 6));
plt.xlabel('Expected Volatility')
plt.ylabel('Expected Return')

Text(0, 0.5, 'Expected Return')